### PR TITLE
NAS-112382 / 21.10 / A short tour on network interface management

### PR DESCRIPTION
**Pull request by themylogin**
@william-gr @rick-mesta do we agree that this is all we want for RC1, shortcuts are redundant because we have autocomplete and we will work on convenient ncurses network configuration dialogs for RC2?

### CODE REVIEW

**Comment by william-gr** [comment]
Yes, I believe so

**Comment by rick-mesta** [comment]
@themylogin: my only concern here was that when I chose `1) Configure network interfaces` I only got the `Sorry, ...` message. My point is, where in these mods  do we actually process the config of the network ? Or are we just hinting at the user that he'll have to select `4) Open TrueNAS CLI Shell` and **then** utter the commands ?

**Comment by themylogin** [comment]
@rick-mesta now instead of `Sorry, ...` we print these man pages and then switch to CLI

**Comment by rick-mesta** [comment]
Ah... ok. Thx for the clarification 👍🏼

**Review by rick-mesta — APPROVED** [review]

**Pull request merged**
